# Generated by Django 4.1.3 on 2022-11-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='list',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
        migrations.AddField(
            model_name='items',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.username'),
        ),
    ]
